package primero;

// Generated 18-dic-2014 10:19:26 by Hibernate Tools 3.4.0.CR1

/**
 * Hbiemps generated by hbm2java
 */
public class Hbiemps implements java.io.Serializable {

	private HbiempsId id;

	public Hbiemps() {
	}

	public Hbiemps(HbiempsId id) {
		this.id = id;
	}

	public HbiempsId getId() {
		return this.id;
	}

	public void setId(HbiempsId id) {
		this.id = id;
	}

}
