package primero;

// Generated 18-dic-2014 10:19:26 by Hibernate Tools 3.4.0.CR1

/**
 * HbiempsId generated by hbm2java
 */
public class HbiempsId implements java.io.Serializable {

	private String dep;
	private long emps;

	public HbiempsId() {
	}

	public HbiempsId(long emps) {
		this.emps = emps;
	}

	public HbiempsId(String dep, long emps) {
		this.dep = dep;
		this.emps = emps;
	}

	public String getDep() {
		return this.dep;
	}

	public void setDep(String dep) {
		this.dep = dep;
	}

	public long getEmps() {
		return this.emps;
	}

	public void setEmps(long emps) {
		this.emps = emps;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HbiempsId))
			return false;
		HbiempsId castOther = (HbiempsId) other;

		return ((this.getDep() == castOther.getDep()) || (this.getDep() != null
				&& castOther.getDep() != null && this.getDep().equals(
				castOther.getDep())))
				&& (this.getEmps() == castOther.getEmps());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDep() == null ? 0 : this.getDep().hashCode());
		result = 37 * result + (int) this.getEmps();
		return result;
	}

}
